# Generated by Django 2.0.5 on 2018-07-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_document_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('books', 'Books'), ('articles', 'Articles'), ('papers', 'Papers')], default='books', max_length=128),
            preserve_default=False,
        ),
    ]
